// <auto-generated />
using FullbarDigital.CadastroDeAlunos.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FullbarDigital.CadastroDeAlunos.Dados.Migrations
{
    [DbContext(typeof(CadastroContext))]
    [Migration("20210815231405_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FullbarDigital.CadastroDeAlunos.Dominio.Models.Aluno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Curso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CursoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Periodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("FullbarDigital.CadastroDeAlunos.Dominio.Models.Curso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeCurso")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("FullbarDigital.CadastroDeAlunos.Dominio.Models.Diciplina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CursoId")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeDiciplina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NotaMinima")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Diciplinas");
                });

            modelBuilder.Entity("FullbarDigital.CadastroDeAlunos.Dominio.Models.Historico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AlunoId")
                        .HasColumnType("bigint");

                    b.Property<long>("DiciplinaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Nota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("DiciplinaId");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("FullbarDigital.CadastroDeAlunos.Dominio.Models.Aluno", b =>
                {
                    b.HasOne("FullbarDigital.CadastroDeAlunos.Dominio.Models.Curso", "AlunoCurso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlunoCurso");
                });

            modelBuilder.Entity("FullbarDigital.CadastroDeAlunos.Dominio.Models.Diciplina", b =>
                {
                    b.HasOne("FullbarDigital.CadastroDeAlunos.Dominio.Models.Curso", "Curso")
                        .WithMany("Diciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("FullbarDigital.CadastroDeAlunos.Dominio.Models.Historico", b =>
                {
                    b.HasOne("FullbarDigital.CadastroDeAlunos.Dominio.Models.Aluno", "Aluno")
                        .WithMany("Historicos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullbarDigital.CadastroDeAlunos.Dominio.Models.Diciplina", "Diciplina")
                        .WithMany("Historicos")
                        .HasForeignKey("DiciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Diciplina");
                });

            modelBuilder.Entity("FullbarDigital.CadastroDeAlunos.Dominio.Models.Aluno", b =>
                {
                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("FullbarDigital.CadastroDeAlunos.Dominio.Models.Curso", b =>
                {
                    b.Navigation("Diciplinas");
                });

            modelBuilder.Entity("FullbarDigital.CadastroDeAlunos.Dominio.Models.Diciplina", b =>
                {
                    b.Navigation("Historicos");
                });
#pragma warning restore 612, 618
        }
    }
}
