/* Create table */
CREATE TABLE TB_CURSO (
	CRS_CODIGO INT NOT NULL IDENTITY PRIMARY KEY,
	CRS_NOME VARCHAR (200),
	CRS_DATA_CRIACAO DATETIME
)

CREATE TABLE TB_DISCIPLINA (
	DIS_CODIGO INT NOT NULL IDENTITY PRIMARY KEY,
	DIS_NOME VARCHAR(200),
	DIS_MIN_APROVADO INT,
	DIS_DATA_CRIACAO DATETIME
)

CREATE TABLE TB_CURSO_DISCIPLINA (
	CDI_CODIGO INT NOT NULL IDENTITY PRIMARY KEY,
	CDI_CRSCODIGO INT FOREIGN KEY (CDI_CRSCODIGO) REFERENCES TB_CURSO (CRS_CODIGO),
	CDI_DISCODIGO INT FOREIGN KEY (CDI_DISCODIGO) REFERENCES TB_DISCIPLINA (DIS_CODIGO),
	CDI_DATA_CRIACAO DATETIME
)

CREATE TABLE TB_ALUNO (
	ALU_CODIGO INT NOT NULL IDENTITY PRIMARY KEY,
	ALU_NOME VARCHAR (400),
	ALU_RA VARCHAR(50),
	ALU_PERIODO VARCHAR(100),
	ALU_FOTO VARCHAR(MAX),
	ALU_CRSCODIGO INT  FOREIGN KEY (ALU_CRSCODIGO) REFERENCES TB_CURSO (CRS_CODIGO),
	ALU_DATA_CRIACAO DATETIME
)

CREATE TABLE TB_ALUNO_DISCIPLINA (
	ADI_CODIGO INT NOT NULL IDENTITY PRIMARY KEY,
	ADI_ALUCODIGO INT FOREIGN KEY (ADI_ALUCODIGO) REFERENCES TB_ALUNO (ALU_CODIGO),
	ADI_DISCODIGO INT FOREIGN KEY (ADI_DISCODIGO) REFERENCES TB_DISCIPLINA (DIS_CODIGO),
	ADI_NOTA DECIMAL,
	ADI_STATUS varchar(10),
	ADI_DATA_CRIACAO DATETIME
)

/* Selects */

SELECT * FROM TB_ALUNO

SELECT * FROM TB_DISCIPLINA

SELECT * FROM TB_CURSO

SELECT * FROM TB_CURSO_DISCIPLINA

SELECT * FROM TB_ALUNO_DISCIPLINA

/* Drop table */

DROP TABLE TB_CURSO_DISCIPLINA

DROP TABLE TB_ALUNO_DISCIPLINA

DROP TABLE TB_ALUNO

DROP TABLE TB_CURSO

DROP TABLE TB_DISCIPLINA




