# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  testebackendapplication:
    image: testebackendapplication
    build:
      context: .
      dockerfile: src/TesteBackEnd.Application/Dockerfile
    ports:
      - 5008:5008
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
