//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace faculdade2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public int IdAluno { get; set; }
        public string Nome { get; set; }
        public string RA { get; set; }
        public string Período { get; set; }
        public string Curso { get; set; }
        public string Status { get; set; }
        public string Foto { get; set; }
        public int IdCurso { get; set; }
    
        public virtual Curso CursoAluno { get; set; }
    }
}
