//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace faculdade2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Disciplina = new HashSet<Disciplina>();
            this.Aluno = new HashSet<Aluno>();
        }
    
        public int IdCurso { get; set; }
        public string NomeCurso { get; set; }
    
        public virtual ICollection<Disciplina> Disciplina { get; set; }
        public virtual ICollection<Aluno> Aluno { get; set; }
    }
}
