//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace faculdade2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplina
    {
        public int IdDisciplina { get; set; }
        public string NomeDisciplina { get; set; }
        public double NotaMinima { get; set; }
        public int IdCurso { get; set; }
    
        public virtual Curso CursoDisciplina { get; set; }
    }
}
