CREATE TABLE TB_USUARIO(
	USU_CODIGO INT IDENTITY,
	USU_LOGIN VARCHAR(50),
	USU_SENHA VARCHAR(MAX),
	USU_DATA_CRIACAO DATETIME NOT NULL,	
	
	CONSTRAINT PK_USACODIGO PRIMARY KEY (USU_CODIGO)
)



CREATE TABLE TB_CURSO(
	CUR_CODIGO INT IDENTITY,
	CUR_NOME VARCHAR(MAX) NOT NULL,
	-- CUR_USUCODIGO_CRIACAO INT,
	-- CUR_DATA_CRIACAO DATETIME,
	-- CUR_USUCODIGO_EDICAO INT,
	-- CUR_DATA_EDICAO DATETIME,
	
	CONSTRAINT PK_CURCODIGO PRIMARY KEY (CUR_CODIGO)
	-- CONSTRAINT FK_CUR_USUCODIGO_CRIACAO FOREIGN KEY (CUR_USUCODIGO_CRIACAO) REFERENCES TB_USUARIO(USU_CODIGO)
	-- CONSTRAINT FK_CUR_USUCODIGO_EDICAO FOREIGN KEY (CUR_USUCODIGO_EDICAO) REFERENCES TB_USUARIO(USU_CODIGO)
)


CREATE TABLE TB_ALUNO(
	ALU_CODIGO INT IDENTITY,
	ALU_NOME VARCHAR(MAX) NOT NULL,
	ALU_REGISTRO_ACADEMICO VARCHAR(10) NOT NULL,
	ALU_PERIODO VARCHAR(5) NOT NULL,
	ALU_CURCODIGO INT,
	ALU_STATUS VARCHAR(10) NOT NULL,
	ALU_FOTO VARBINARY(MAX),
	-- ALU_USUCODIGO_CRIACAO INT,
	-- ALU_DATA_CRIACAO DATETIME,
	-- ALU_USUCODIGO_EDICAO INT,
	-- ALU_DATA_EDICAO DATETIME,
	
	CONSTRAINT PK_ALUCODIGO PRIMARY KEY (ALU_CODIGO),
	CONSTRAINT FK_ALU_CURCODIGO FOREIGN KEY (ALU_CURCODIGO) REFERENCES TB_CURSO (CUR_CODIGO)
	-- CONSTRAINT FK_ALU_USUCODIGO_CRIACAO FOREIGN KEY (ALU_USUCODIGO_CRIACAO) REFERENCES TB_USUARIO(USU_CODIGO)
	-- CONSTRAINT FK_ALU_USUCODIGO_EDICAO FOREIGN KEY (ALU_USUCODIGO_EDICAO) REFERENCES TB_USUARIO(USU_CODIGO)
)


CREATE TABLE TB_DISCIPLINA(
	DIS_CODIGO INT IDENTITY,
	DIS_NOME varchar(max) NOT NULL,
	DIS_NOTA_APROVACAO DECIMAL(2,1) NOT NULL,
	DIS_CURCODIGO INT,
	-- DIS_USUCODIGO_CRIACAO INT,
	-- DIS_DATA_CRIACAO DATETIME,
	-- DIS_USUCODIGO_EDICAO INT,
	-- DIS_DATA_EDICAO DATETIME,
	
	CONSTRAINT PK_DISCODIGO PRIMARY KEY(DIS_CODIGO),
	CONSTRAINT FK_DIS_CURCODIGO FOREIGN KEY (DIS_CURCODIGO) REFERENCES TB_CURSO (CUR_CODIGO)
	-- CONSTRAINT FK_DIS_USUCODIGO_CRIACAO FOREIGN KEY (DIS_USUCODIGO_CRIACAO) REFERENCES TB_USUARIO(USU_CODIGO)
	-- CONSTRAINT FK_DIS_USUCODIGO_EDICAO FOREIGN KEY  (DIS_USUCODIGO_EDICAO) REFERENCES TB_USUARIO(USU_CODIGO)
)


CREATE TABLE TB_ALUNO_NOTA(
	ALN_CODIGO INT IDENTITY,
	ALN_ALUCODIGO INT,		
	ALN_DISCODIGO INT,
	ALN_NOTA DECIMAL(2,1) NOT NULL,
	-- ALN_USUCODIGO_CRIACAO INT,
	-- ALN_DATA_CRIACAO DATETIME,
	-- ALN_USUCODIGO_EDICAO INT,
	-- ALN_DATA_EDICAO DATETIME,
	
	CONSTRAINT PK_ALN_CODIGO PRIMARY KEY (ALN_CODIGO),
	CONSTRAINT FK_ALN_ALUCODIGO FOREIGN KEY (ALN_ALUCODIGO) REFERENCES TB_ALUNO (ALU_CODIGO),
	CONSTRAINT FK_ALN_DISCODIGO FOREIGN KEY (ALN_DISCODIGO) REFERENCES TB_DISCIPLINA (DIS_CODIGO)
	-- CONSTRAINT FK_ALN_USUCODIGO_CRIACAO FOREIGN KEY (ALN_USUCODIGO_CRIACAO) REFERENCES TB_USUARIO(USU_CODIGO)
	-- CONSTRAINT FK_ALN_USUCODIGO_EDICAO FOREIGN KEY  (ALN_USUCODIGO_EDICAO) REFERENCES TB_USUARIO(USU_CODIGO)
)




DROP TABLE TB_ALUNO_NOTA
DROP TABLE TB_DISCIPLINA
DROP TABLE TB_ALUNO
DROP TABLE TB_CURSO

